### ISSUE TITLE
Android inline mode

### ISSUE THREAD

**Issue by JeffreyWardman** [react-native-datetimepicker/datetimepicker#823] opened 2023-10-07 01:18 UTC
# Feature request

Having an inline mode for Android allows for consistency between iOS and Android platforms when iOS uses inline. Currently, if iOS is inline, Android still requires a modal, resulting in a different user workflow.

**Comment by vonovak** [comment] 2023-10-09 10:15
Hello and thanks for reporting,
this is a dupe of https://github.com/react-native-datetimepicker/datetimepicker/issues/14

as mentioned [here](https://github.com/react-native-datetimepicker/datetimepicker/issues/14#issuecomment-581058401), contributions or sponsorships are welcome
Thank you 🙂

**Closed by vonovak** 2023-10-09 10:15 UTC
