### ISSUE TITLE
How can i open directly calendar popup in IOS? 

### ISSUE THREAD

**Issue by Alpacora** [react-native-datetimepicker/datetimepicker#504] opened 2021-08-31 18:10 UTC
# Question

Hello guys! please help-me. I want to know if its possible open Calendar PopUp in IOS with custom button, if yes, please tell-me. Thanks in advanced.

**Comment by cesargdm** [comment] 2021-09-01 16:44
Apparently this is a duplicate of https://github.com/react-native-datetimepicker/datetimepicker/issues/483

**Comment by vonovak** [comment] 2021-12-11 13:48
hello, thanks for asking. I'm not aware of such way.

**Closed by vonovak** 2021-12-11 13:48 UTC
