### ISSUE TITLE
Expo managed workflow, android text buttons not visible

### ISSUE THREAD

**Issue by couoheduardo** [react-native-datetimepicker/datetimepicker#557] opened 2022-01-15 00:35 UTC
# Bug report

When the modal opens, in display={'spinner'} the text cancel and accept is not visible!

currently im using expo 43, this happens in android.

**Comment by kelvinndmo** [comment] 2022-01-15 07:53
Use EAS Build and expo dev client for development

**Comment by pwfcurry** [comment] 2022-01-21 12:34
Related: https://github.com/react-native-datetimepicker/datetimepicker/issues/543#issuecomment-1006427288

**Comment by webdevmario** [comment] 2022-05-16 14:49
I left a comment in issue #543 about my scenario but this definitely started to happen once we upgraded to Expo SDK 45.

**Comment by vonovak** [comment] 2022-07-25 22:42
closing as duplicate of #543

**Closed by vonovak** 2022-07-25 22:42 UTC
