### ISSUE TITLE
custom width and height

### ISSUE THREAD

**Issue by Salmankhan033** [react-native-datetimepicker/datetimepicker#579] opened 2022-03-11 12:44 UTC
I want to give some width to Piker in react native
but it can't apply on time picker

<DateTimePicker
						// testID={'date'}
						value={date}
						mode={'date'}
						is24Hour={true}
						display="default"
						onChange={onChangeDate}
						style={{width: wp('40%'), backgroundColor: 'red', flex: 1, height: hp('10%')}}
					/>
 <img src="https://user-images.githubusercontent.com/58082294/157869121-2e022714-ff59-4876-9178-8df1ddf4cb0c.png" alt="Drawing"  width="200" height="350"/>

**Comment by vonovak** [comment] 2022-03-13 03:56
closing as duplicate of #409

**Closed by vonovak** 2022-03-13 03:56 UTC
