### ISSUE TITLE
DateTimePicker input full width

### ISSUE THREAD

**Issue by Mihai-github** [react-native-datetimepicker/datetimepicker#549] opened 2022-01-02 12:58 UTC
Hi,

I have the following code and I cannot make the DateTimePicker Input for a selected date to take the full width of the container, has anyone encountered this problem and has come with a solution for this problem?

Code example:

```
<DateTimePicker
                            defaultDate={chosenDate}
                            minimumDate={new Date(1930, 1, 1)}
                            maximumDate={new Date()}
                            locale={'en'}
                            themeVariant="dark"
                            timeZoneOffsetInMinutes={undefined}
                            modalTransparent={false}
                            animationType={'fade'}
                            androidMode={'default'}
                            placeHolderText="Select date"
                            textStyle={{ color: 'green' }}
                            placeHolderTextStyle={{ color: '#d3d3d3' }}
                            onDateChange={onDateChange}
                            disabled={false}
                            value={chosenDate}
                            mode="date"
                        />
```

**Comment by vonovak** [comment] 2022-01-08 23:53
duplicate of https://github.com/react-native-datetimepicker/datetimepicker/issues/409

**Closed by vonovak** 2022-01-08 23:53 UTC
