### ISSUE TITLE
Modal is opening automatically

### ISSUE THREAD

**Issue by vishnuc** [react-native-datetimepicker/datetimepicker#600] opened 2022-04-18 17:59 UTC
HI , I have simple setup like below

https://snack.expo.dev/3vFq4kiR8

But Datepicker is opening automatically in android , but not in ios.

How to stop datepicker to open automatically in android , thanks.

**Comment by jereztech** [comment] 2022-05-07 01:23
+1

**Comment by jereztech** [comment] 2022-05-13 02:10
Hi @amerikan, the problem is that if `DateTimePickerAndroid` is a Modal, when the user Cancels or clicks outside the Modal, the Modal closes without invoking `setShow(false)`, then when triggering any other functionality, React Native renders again and forces the Modal to open because it still continues `show = true`, to solve this problem it is convenient to have an `onDismiss` method that, in addition to being used by `onCancel`, can be used by programmers to call `setShow(false)`

**Comment by polygbrl** [comment] 2022-05-17 12:51
> Hi @amerikan, the problem is that if DateTimePickerAndroid is a Modal, when the user Cancels or clicks outside the Modal, the Modal closes without invoking setShow(false), then when triggering any other functionality, React Native renders again and forces the Modal to open because it still continues show = true, to solve this problem it is convenient to have an onDismiss method that, in addition to being used by onCancel, can be used by programmers to call setShow(false)
> 
> EUREKA (update): we can call `setShow(false)` when `onChange` returns undefined (this works for me, hope it helps others)

@jereztech, I just wanted to add that onChange carries out the type of event:
```javascript
Object {
  "nativeEvent": Object {},
  "type": "dismissed",
}
```
So to avoid setting a date when the user dismisses, you could verify the value of  `event.type` on change:
```javascript
const onChange = (event, value) => {
    if (event.type === 'dismissed') { 
        setShow(false);
    }
    else if (event.type === 'set') {
        setDate(value);
    }
    // and so on...
}
```

**Comment by vonovak** [comment] 2022-08-20 09:27
closing as resolved, thank you! :)

**Closed by vonovak** 2022-08-20 09:27 UTC

**Comment by chunghn** [comment] 2022-09-08 04:04
My modal still reopens when pressing the positive button after applying the above solution. For someone who still has the issue, this works for me:

```js
const onChange = (event, selectedDate) => {
    if (event.type === "dismissed" || event.type === "set") {
        setShow(false);
    } 
    if (selectedDate) {
    // ...
    }
}

**Comment by nihil-pro** [comment] 2023-06-04 09:40
This is disgusting behavior, why open it without asking?

**Comment by geoffcfchen** [comment] 2024-04-17 19:39
My solution

  const [show, setShow] = useState(false);
const [date, setDate] = useState(new Date());
  
    const onDateChange = (event, date) => {
    if (event.type === "dismissed" || event.type === "set") {
      setShow(false);
    }
    setDate(date);

  };

{Platform.OS == "ios" ? (
                <DateTimePicker
                  testID="dateTimePicker"
                  value={date}
                  mode="date"
                  is24Hour={true}
                  display="default"
                  onChange={onDateChange}
                />
              ) : (
                <>
                  <Button
                    mode="outlined"
                    onPress={() => {
                      setShow(true);
                    }}
                  >
                    {" "}
                    {date.toLocaleDateString("en-US", {
                      month: "short", // "Apr"
                      day: "numeric", // "5"
                      year: "numeric", // "2024"
                    })}
                  </Button>
                  {show && (
                    <DateTimePicker
                      testID="dateTimePicker"
                      value={date}
                      mode="date"
                      is24Hour={true}
                      display="default"
                      onChange={onDateChange}
                    />
                  )}
                </>
              )}
