### ISSUE TITLE
Changing text color of iOS picker

### ISSUE THREAD

**Issue by markwindsorr** [react-native-datetimepicker/datetimepicker#308] opened 2020-10-15 14:33 UTC
![Screen Shot 2020-10-15 at 12 03 16 PM](https://user-images.githubusercontent.com/23028549/96144136-6a119d80-0ede-11eb-9465-80e796220e66.png)

I need to change the color of this text.

Edit: eventually this issue evolved to report that `textColor` prop does not work when `display="spinner"` which is a bug. textColor will not work for other `display` modes

**Comment by williamhaley** [comment] 2020-10-15 23:06
I was struggling through that myself. The `textColor` prop should work to set the picker color, as far as I understand it - https://github.com/react-native-datetimepicker/datetimepicker#textColor-optional-ios-only

However, I think that this prop (in iOS 14) only works if you're using `spinner` for `display`?

> Allows changing of the textColor of the date picker. Has effect only when display is "spinner".

Which seems to be backed up by the code.

https://github.com/react-native-datetimepicker/datetimepicker/blob/master/ios/RNDateTimePickerManager.m#L87

It looks like `UIDatePickerStyleWheels` corresponds to `spinner` https://github.com/react-native-datetimepicker/datetimepicker/blob/master/ios/RNDateTimePickerManager.m#L26

**Comment by pedromarta** [comment] 2020-10-17 21:30
https://github.com/pedromarta/datetimepicker/commit/8a58077e412d5258c881484619cf754cc7acc337

That is my approach to an eventual fix, it works nicely, although it's done on the React side.

`heightStyle` is being used as a dependency, since it also gets set in state after the 1st layout. 

`RCT_CUSTOM_VIEW_PROPERTY(textColor, UIColor, RNDateTimePicker)` is being blocked due to #247 (the issue is still live after beta). On that problem, it seems that textColor is being set before the actual date picker style changes to `UIDatePickerStyleWheels` (?).

By reaching `RCT_CUSTOM_VIEW_PROPERTY(textColor, UIColor, RNDateTimePicker)` after the 1st layout with the `textColor` value change from undefined to the actual value passed through props, the change won't be blocked by 
```
if (@available(iOS 14.0, *) && view.datePickerStyle != UIDatePickerStyleWheels) {
    // prevents #247
    return;
  }
```
since we'll meet the `view.datePickerStyle != UIDatePickerStyleWheels` condition at that time.

@vonovak Would this be worthy of a PR?

**Comment by vonovak** [comment] 2020-10-17 21:37
@pedromarta sorry, I don't follow. And I don't really understand what https://github.com/pedromarta/datetimepicker/commit/8a58077e412d5258c881484619cf754cc7acc337 is about.

Would you expand on that?

**Comment by pedromarta** [comment] 2020-10-17 21:44
```
if (@available(iOS 14.0, *) && view.datePickerStyle != UIDatePickerStyleWheels) {
    // prevents #247
    return;
  }
```

That stretch of code in `RNDateTimePickerManager.m` blocks `textColor` from being set in devices with iOS 14.0. `view.datePickerStyle` only gets changed to `UIDatePickerStyleWheels` after that.

In practical terms, the modal will have the original clear text color that gets lost in the original white background.

**Comment by williamhaley** [comment] 2020-10-18 03:52
What you're saying makes sense to me @pedromarta. That explains some behavior around textColor I've seen the past few days but have been too lazy to identify. See attached gif.

My app is built with `textColor="blue"` for the `DateTimePicker`, but that textColor does not take effect when the app is launched. Only when the `textColor` is changed does that prop seem to matter. Then the DateTimePicker re-renders and actually uses the value.

![textColor](https://user-images.githubusercontent.com/1851748/96358301-63944900-10cb-11eb-84f2-1b34d98c9948.gif)

**Comment by tgreco** [comment] 2020-12-06 18:21
@vonovak any update on this one?
I am having trouble trying to style this component on ios 14.

**Comment by vonovak** [comment] 2020-12-06 21:01
Hello, I'm not aware of any way to change the color of text in OP's screenshot. The `textColor` prop only works for `UIDatePickerStyleWheels` which corresponds to `display="spinner"` although there apparently are issues as seen in https://github.com/react-native-datetimepicker/datetimepicker/issues/308#issuecomment-711112673

**Comment by vonovak** [comment] 2020-12-06 21:10
@pedromarta it'd be nice to fix the issue you fixed in https://github.com/pedromarta/datetimepicker/commit/8a58077e412d5258c881484619cf754cc7acc337 but instead of fixing it from JS, I would prefer to see the fix done in the native module (when color prop is set, we should remember it, and then when the display prop changes to `UIDatePickerStyleWheels` then we would recover that color, if that makes sense.?

**Comment by sayo96** [comment] 2020-12-12 05:51
Even having display="spinner" is not allowing me to change text color. Here is a sample of my code:
```
 <DateTimePicker
      testID="dateTimePicker"
      value={new Date(date)}
      mode="date"
      display="spinner"
      textColor="red"
      onChange={Platform.OS === 'android' ? handleChangeAndroid : handleChange}
    />
```
I'm on expo sdk 38 and i'm using `@react-native-community/datetimepicker:3.0.6`

**Comment by alesdvorakcz** [comment] 2021-01-26 11:39
I am having same problem. v3.0.9 looks like it ignores textColor on ios.
```
<DateTimePicker
   mode="datetime"
   display="inline"
   textColor="red"
   onChange={...}
   value={...}
/>
```
<img width="246" alt="image" src="https://user-images.githubusercontent.com/1890782/105840410-f3705a00-600d-11eb-907e-e288749d2275.png">

**Comment by stefan-girlich** [comment] 2021-02-05 10:34
@alesdvorakcz could you please add your iOS version and device type to your comment?

Since discussion of issue #247 has been [merged](https://github.com/react-native-datetimepicker/datetimepicker/issues/247#issuecomment-766682478) with the discussion of this issue, I'd like to highlight again that there still seem to be to particular crashes related to `react-native-datetimepicker` v3.0.2 and iOS 14.x:

* `Cannot read property 'getDefaultDisplayValue' of undefined`(see #306, currently still experiencing this using library v3.0.9 with expo v38.0.8 on iOS 14.4)
*  `[_UIDatePickerIOSCompactView setHighlightsToday:]: unrecognized selector sent to instance 0x7f7fc7e0ddc0` (see #247)

**Comment by fix777** [comment] 2021-02-18 14:58
> I am having same problem. v3.0.9 looks like it ignores textColor on ios.
> 
> ```
> <DateTimePicker
>    mode="datetime"
>    display="inline"
>    textColor="red"
>    onChange={...}
>    value={...}
> />
> ```
> 
> <img alt="image" width="246" src="https://user-images.githubusercontent.com/1890782/105840410-f3705a00-600d-11eb-907e-e288749d2275.png">

Hi, there.
Can I ask how you changed the background color to grey and text color to white?

**Comment by alesdvorakcz** [comment] 2021-02-22 08:11
> > I am having same problem. v3.0.9 looks like it ignores textColor on ios.
> > ```
> > <DateTimePicker
> >    mode="datetime"
> >    display="inline"
> >    textColor="red"
> >    onChange={...}
> >    value={...}
> > />
> > ```
> > 
> > 
> > <img alt="image" width="246" src="https://user-images.githubusercontent.com/1890782/105840410-f3705a00-600d-11eb-907e-e288749d2275.png">
> 
> Hi, there.
> Can I ask how you changed the background color to grey and text color to white?

Its just default dark theme on ios/iphone

**Comment by alesdvorakcz** [comment] 2021-02-22 08:18
@fix777 Its not crashing, just the color property is not working. I have ios 14.3

**Comment by thisisgit** [comment] 2021-03-31 05:26
It says [here](https://github.com/react-native-datetimepicker/datetimepicker#textcolor-optional-ios-only) that the textColor property only `has effect only when display is "spinner".`

But I'm also here while looking for possible solution to change that default system blue color to another color in iOS 14 datepicker.
Anyone knows solution to that?

**Comment by SergeyShalapuda** [comment] 2021-06-07 12:17
Even with the latest "datetimepicker" version "^3.5.2" I saw the same issue with the "white text on white background" with "react-native-modal-datetime-picker" in the Expo app.

Seems like it may be related to the "userInterfaceStyle": "light", in the Expo app.json settings when the iPhone in the dark mode. The solution I found is to update "textColor" property programmatically (because it works if use set it after  <DateTimePickerModal> became visible.

```
  const [textColor, setTextColor] = useState('black');
...
  const iOsColorFix = () => {
    setTimeout(() => {
      setTextColor(prevState => prevState === "green" ? "black" : "green"); // It is important to change the textColor state on some different value
    }, 0);
  };
...
<DateTimePickerModal
        isVisible={isDatePickerVisible}
        mode="date"
        date={date ? new Date(date) : new Date()}
        onConfirm={handleConfirm}
        onCancel={hideDatePicker}
        textColor={textColor}
        themeVariant="light"
      />
```

**Comment by gelfer** [comment] 2021-07-01 09:21
> Even with the latest "datetimepicker" version "^3.5.2" I saw the same issue with the "white text on white background" with "react-native-modal-datetime-picker" in the Expo app.
> 
> Seems like it may be related to the "userInterfaceStyle": "light", in the Expo app.json settings when the iPhone in the dark mode. The solution I found is to update "textColor" property programmatically (because it works if use set it after became visible.
> 
> ```
>   const [textColor, setTextColor] = useState('black');
> ...
>   const iOsColorFix = () => {
>     setTimeout(() => {
>       setTextColor(prevState => prevState === "green" ? "black" : "green"); // It is important to change the textColor state on some different value
>     }, 0);
>   };
> ...
> <DateTimePickerModal
>         isVisible={isDatePickerVisible}
>         mode="date"
>         date={date ? new Date(date) : new Date()}
>         onConfirm={handleConfirm}
>         onCancel={hideDatePicker}
>         textColor={textColor}
>         themeVariant="light"
>       />
> ```

This works for me. Thanks.

**Comment by dslatkin** [comment] 2022-05-11 00:21
> Even with the latest "datetimepicker" version "^3.5.2" I saw the same issue with the "white text on white background" with "react-native-modal-datetime-picker" in the Expo app.
> 
> Seems like it may be related to the "userInterfaceStyle": "light", in the Expo app.json settings when the iPhone in the dark mode. The solution I found is to update "textColor" property programmatically (because it works if use set it after became visible.

Thanks for this, a variation of this also worked for us. Our implementation looks along the lines of:

```ts
const [textColor, setTextColor] = useState<string>("black");

useMemo(() => {
  if (isPickerOpen) {
    setTimeout(() => setTextColor("black"), 0);
  }
  if (!isPickerOpen) {
    setTimeout(() => setTextColor(""), 0);
  }
}, [isPickerOpen, setTextColor]);
```

```tsx
<DateTimePicker
    mode="datetime"
    isVisible={isPickerOpen}
    textColor={textColor}
    ...
/>
```

**Comment by vonovak** [comment] 2022-07-25 22:49
Hello, customizing the text colors is now possible via the `accentColor` and `themeVariant` props.

Thank you 🙂

**Closed by vonovak** 2022-07-25 22:49 UTC
Labels: good first issue

**Comment by mikeRChambers610** [comment] 2022-09-10 02:28
I have this issue for the calendar. On IPhone you cant even see the calendar because the tet is white on a white screen. I cant change the text color. Is there any update? This seems like a simple ask and the issue is opened for 2 years now.
