### ISSUE TITLE
Calendar start from monday instead of sunday

### ISSUE THREAD

**Issue by andib0** [react-native-datetimepicker/datetimepicker#820] opened 2023-10-04 08:48 UTC
Have the ability to make the calendar start from monday instead of sunday:
![Capture](https://github.com/react-native-datetimepicker/datetimepicker/assets/129665998/57d3d3d3-e667-476a-9b33-c87c621ec922)

**Comment by vonovak** [comment] 2023-10-06 16:39
Hello and thanks for asking,
this is a duplicate of https://github.com/react-native-datetimepicker/datetimepicker/issues/196
Thank you 🙂

**Closed by vonovak** 2023-10-06 16:39 UTC
