### ISSUE TITLE
Add Expo Config plugin for android colors

### ISSUE THREAD

**Issue by iway1** [react-native-datetimepicker/datetimepicker#742] opened 2023-03-23 21:00 UTC
# Feature request

If this package included an expo config plugin for changing the date picker / time picker colors, that'd be really great because it could make it much easier for devs to change colors on Android.

## Why it is needed

Changing colors for the android pickers is a massive pain (and impossible in Expo without a config plugin). With an included config plugin, this package could make it as easy as possible given the constraints of having to modify `styles.xml` on android to change those colors. 

## Possible implementation / Code Sample

app.json
```json
{
  "plugins": [
    "@react-native-community/datetimepicker", 
    {
      "darkMode": {
         "accentColor": "#662C69",
         "textColor": "#000000"
       },
       "lightMode": {
          "accentColor": "#662C69",
          "textColor": "#662C69"
       }
    }
  ]
}
```

styles.xml
```xml
<resources>
  <!-- Stuff that gets added  -->
  <style name="DialogTimePicker.Theme" parent="Theme.AppCompat.Light.Dialog">
    <item name="colorAccent">#662C69</item>
    <item name="android:textColorPrimary">#662C69</item>
  </style>
  <style name="DialogTimePicker.Theme" parent="Theme.AppCompat.Dark.Dialog">
    <item name="colorAccent">#662C69</item>
    <item name="android:textColorPrimary">#000000</item>
  </style>
</resources>
```

Haven't tested the above `styles.xml`, but something like this should work and be possible

For reference: https://github.com/react-native-datetimepicker/datetimepicker/issues/20#issuecomment-1107793898

**Comment by vonovak** [comment] 2023-07-11 16:29
Hello and thanks for reporting,
I'm closing this as a duplicate of https://github.com/react-native-datetimepicker/datetimepicker/issues/20

please feel free to open a PR for this, or consider sponsoring the development of the package. This is on my watchlist but I have a ton of other projects and it's hard to prioritize this with the current budget: https://opencollective.com/react-native-datetimepicker
Thank you 🙂

**Closed by vonovak** 2023-07-11 16:29 UTC
