### ISSUE TITLE
Crash when I select the date using the keyboard

### ISSUE THREAD

**Issue by raphaelPloomes** [react-native-datetimepicker/datetimepicker#343] opened 2020-11-18 15:13 UTC
It only happens on Android, whether in date or time mode.

Steps to reproduce:

1 - Select input via keyboard

![picker1](https://user-images.githubusercontent.com/69814263/99547332-2eaf3680-2996-11eb-8aa9-400f8cf7cb51.png)

2 - Change the value

![picker2](https://user-images.githubusercontent.com/69814263/99547554-6ae29700-2996-11eb-928d-b440c5010a20.png)

At that moment, the keyboard appears and soon after the app crashes

![picker3](https://user-images.githubusercontent.com/69814263/99547659-8baaec80-2996-11eb-94fa-41c50d48988e.png)

Here is my code:

`
 <RNDateTimePicker
     value={this.state.date || new Date()}
     display={'clock'}
     mode={'time'}
            onChange={(event, newDate) => {
              this.setState({ showTimePickerAndroid: false });
              this.setDate(newDate);
            }}
          />
`

Versions:

@react-native-community/datetimepicker": "^3.0.5"
react-native: "~0.61.5"
Android 10

**Comment by IvanRozinko** [comment] 2020-11-23 10:37
Hi! I'm facing the same issue 

 "@react-native-community/datetimepicker": "^2.2.2",
"react-native": "0.61.5",

**Comment by vonovak** [comment] 2022-03-13 15:57
Hello 👋 ,
I cannot reproduce the issue with v6 in our example app.

With that, I'm closing the issue,
Thank you! 🙂

**Closed by vonovak** 2022-03-13 15:57 UTC
Labels: good first issue
