### ISSUE TITLE
iOS 14 Time picker crash

### ISSUE THREAD

**Issue by Erik1291** [react-native-datetimepicker/datetimepicker#286] opened 2020-09-22 15:40 UTC
# Bug report

## Summary

On iOS 14 when pressing the time picker and trying to change the time with the keyboard, the system crashes.
Error: 
Argument 0 (NSNumber) of UIManager.measure must not be null

## Environment info

`react-native info` output:

```bash
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 45.46 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: x.x.x

## Steps to reproduce

1. Create a DateTimePicker only with mode="time"
2. Press on the default time
3. Press on the time again to open keyboard.
4. System crashes

Describe what you expected to happen:

1. no Crash

## Reproducible sample code

![IMG_F4B5C2C40C2A-1](https://user-images.githubusercontent.com/71717898/93905247-0808b280-fcfb-11ea-845d-d7657015ba74.jpeg)

**Comment by sitanjob** [comment] 2020-09-23 07:04
Can you send your code? From my point just comment textColor 
```
<DateTimePicker
        value={value}
        onChange={onChange}
        mode={'time'}
        // textColor="black"
      />
```

**Comment by IrvanMahardhika** [comment] 2020-09-24 04:42
![IMG_B31F26E38799-1](https://user-images.githubusercontent.com/53810147/94100306-837f7680-fe57-11ea-86bf-9bbbddcfa6c0.jpeg)

Happens to me too since installing ios 14 last week.
My code is :
```
<DateTimePicker  
          testID='dateTimePicker'
          value={dateState}
          mode='date'
          is24Hour={true}
          display='default'
          onChange={(event, date) =>setDateState(date)}
          style={someStyle}
          textColor={white}
/>
```
I'm using React Native 0.61 and run it on iphone X.

**Comment by Erik1291** [comment] 2020-09-24 13:25
```
<DateTimePicker 
						value={this.state.date}
						mode="time"
						is24Hour={true}
						display="default"
						style={{height:45, width:150, backgroundColor:'#FFF'}}
						onChange={this.setDate} />
```

I tried it without style, without display and so on. Still not working.

**Comment by Gentlee** [comment] 2020-09-24 14:15
textColor is the cause.

**Comment by Erik1291** [comment] 2020-09-24 14:27
I did not set any text color...
I upgraded my react native and all dependencies.
The dump/error is gone.

**Comment by harveyconnor** [comment] 2020-09-27 13:22
Yep text color is the cause.

**Comment by andreasadelino** [comment] 2020-10-23 18:10
I'm facing this exact same error in Android.

**Comment by vonovak** [comment] 2022-01-08 23:58
this is fixed here https://github.com/react-native-datetimepicker/datetimepicker/blob/85c7a701677b60d86bef498fcd470cc67197c200/ios/RNDateTimePickerManager.m#L123
so closing :)

**Closed by vonovak** 2022-01-08 23:58 UTC
Labels: good first issue
