### ISSUE TITLE
you can change the native color that comes by default of android

### ISSUE THREAD

**Issue by Alexanderwags** [react-native-datetimepicker/datetimepicker#488] opened 2021-07-06 16:26 UTC
I want to change the background color, I don't want it green

**Comment by traviswsims** [comment] 2021-07-07 18:11
Wish the OP phrased his comment better, but I am also interested in styling the Android time picker.  Any suggestions?  Thank you!

**Comment by Alexanderwags** [comment] 2021-07-09 01:00
![Screenshot_12](https://user-images.githubusercontent.com/26121628/125007923-622af800-e02f-11eb-9fd7-412b05d363e6.png)
hello @traviswsims ,If you argue wrong, what I want is to change the native color of android by default I get green, I would like it to be orange.

**Comment by Andrea-Arguello** [comment] 2021-07-09 01:11
#20 and #340 seem to be similar issues, have you tried any of the solutions mentioned in the comments?

**Comment by sphrases** [comment] 2021-08-12 12:43
🙋I really need this feature too! The solutions from #20 and #340 seem to only work statically with bare workflow (Not with standard Expo) The solutions further suggest that the problem lies with android itself.

**Comment by vonovak** [comment] 2021-12-11 23:26
duplicate of #20

**Closed by vonovak** 2021-12-11 23:26 UTC
