### ISSUE TITLE
Android Time Picker: Re-open default on different time than the value

### ISSUE THREAD

**Issue by periabyte** [react-native-datetimepicker/datetimepicker#73] opened 2019-12-26 18:50 UTC
# Question

I've been trying to implement a custom wrapper for `datetimepicker` it works as expected except with one scenario, when you already selected a time `12:00 AM` then submit it'll return the proper time `yyyy-mm-dd:00:00:00` (I'll save this to the state and then assign it as the `value` prop of the datetimepicker) when I re-open the picker it'll not default to the current value `12:00 AM` but default to a later time `8:00 AM`

```js
_onChange = (e, time) => this.setState({ showPicker: false, value: time })
// render
<View style={[styles.mainContainer, mainContainerStyle]}>
	<TouchableOpacity onPress={this._togglePicker}>
		<View style={[styles.datePickerContainer, containerStyle]}>
			<Icon
				name="md-time"
				style={[styles.datePickerIcon, iconStyle]}
				type="Ionicons"
			/>
			<Text>
			{props.value
				? moment(props.value || undefined).format(timeFormat)
				: placeholderText}
			</Text>
		</View>
	</TouchableOpacity>
	{showPicker ? (
		<DateTimePicker
			display="clock"
			mode="time"
			value={value}
			onChange={this._onChange}
		/>
	) : null}
</View>
```

**Comment by vonovak** [comment] 2022-03-12 15:17
Hello and thanks for reporting,
because the issue is so old I'm going to close it, as it the library has evolved since then.
Feel free to reopen (please follow the issue template).
Thank you

**Closed by vonovak** 2022-03-12 15:17 UTC
