### ISSUE TITLE
Android spinner display type does hidden button labels

### ISSUE THREAD

**Issue by jkdowdle** [react-native-datetimepicker/datetimepicker#655] opened 2022-09-09 02:00 UTC
# Bug report

## Summary

It appears that if I attempt to use the `display` prop on android I get unexpected behavior where the button labels are transparent. I first noticed this trying to use `{ mode: 'time', display: 'spinner' }`. However this seems to happen with any `display: 'spinner'`, see screen shots

I've tried this with a physical device as well as a simulator and getting the same results. I have been using expo so the version has been `@react-native-community/datetimepicker@6.2.0` but I've also attempted to install `@react-native-community/datetimepicker@6.3.2` with the same behavior

I get the same behavior between using the component vs the android imperative api 

| display spinner | onPress | without display prop / default (ok/cancel visible) |
| - | - | - |
| <img width="547" alt="image" src="https://user-images.githubusercontent.com/19804196/189254977-e416eaa1-1c35-4f8f-ba11-9a82111425c6.png"> | <img width="547" alt="image" src="https://user-images.githubusercontent.com/19804196/189255040-c01dc4eb-e0c2-4c9f-b383-92e2592ad9fd.png"> | <img width="547" alt="image" src="https://user-images.githubusercontent.com/19804196/189256473-cbdceaa2-8442-4257-aea8-25dd857e52f7.png"> |

## Reproducible sample code

Repo: https://github.com/jkdowdle/android-datetimepicker-issue

```
import React from 'react';
import { View, Button } from 'react-native';
import { DateTimePickerAndroid } from '@react-native-community/datetimepicker';

export const Debug = () => {
  return (
    <View>
      <Button
        title="hello"
        onPress={() => {
          DateTimePickerAndroid.open({
            value: new Date(),
            display: 'spinner',
          });
        }}
      />
    </View>
  );
};
```

## Steps to reproduce

1. Render on an android device a button that opens the date picker
2. click the button
3. **Note** that the labels appear to be missing (you can still interact with them, but appear invisible to the end user)

Describe what you expected to happen:

I expected that we could render an android date or time spinner and have the button labels show up as expected 

## Environment info

`expo@46.0.8`

`npx react-native info` output:

```bash
$ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 102.62 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2022.08.08.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/joshd/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 26
      System Images: android-25 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.5 => 0.69.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.70.0 is now available (your project is running on v0.69.5).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.70.0.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.69.5.
info To upgrade, run "react-native upgrade".

```

datetimepicker version: 6.2.0 / 6.3.2

Android version: 10.0

Thank you so much!

**Comment by jkdowdle** [comment] 2022-09-09 02:15
Interesting related issue, with these props the primary color in the Picker seems to change, but we still have the invisible buttons. Seems like `display` is not safe to use on android?

```
DateTimePickerAndroid.open({
  value,
  mode: "date",
  display: "calendar",
});
```

<img width="300" alt="image" src="https://user-images.githubusercontent.com/19804196/189257728-28179945-f350-4480-9f9e-b7fcc9a27d3c.png">

**Comment by vonovak** [comment] 2022-09-16 08:45
hello and thanks for reporting, I'm closing it as duplicate of #543.

it has something to do with using expo, hope to look into it soon!

**Closed by vonovak** 2022-09-16 08:45 UTC
