### ISSUE TITLE
datepicker don't apppear  on ios

### ISSUE THREAD

**Issue by caolong0204** [react-native-datetimepicker/datetimepicker#484] opened 2021-06-29 07:39 UTC
# Bug report
I can't see datepicker on Simulator or Real Device IOS

## Summary
My project using RN 0.64 and  react-native-datetimepicker version 3.5.2
My code work on Android But IOS is not. I don't see any datepicker 

## Reproducible sample code
![image](https://user-images.githubusercontent.com/66582805/123756183-da364700-d8e6-11eb-98ec-f000ceaf98b8.png)

## Steps to reproduce

1. I create a DateTimePicker and button to open DateTimePicker be like sample code
2.Click Button and don't has anything happen

Describe what you expected to happen:

1. When Click Button , DatePicker will show

## Environment info

`npx react-native info` output:

```bash
# paste it here
System:
    OS: macOS 11.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 347.96 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

datetimepicker version: 3.5.2

iOS version: 14.5

**Comment by sofian-io** [comment] 2021-07-05 12:16
I have the same issue on iOS 14.5 the setShow(true) only displays the time picker (gray box in screenshot below) and you need to press it again to open the time picker modal.

datetimepicker version: 3.5.2

iOS version: 14.5

<img width="288" alt="Screenshot 2021-07-05 at 14 13 39" src="https://user-images.githubusercontent.com/11960001/124469930-40b1de00-dd9b-11eb-9a9e-5ccff495d0f5.png">

**Comment by mstibbard** [comment] 2021-07-07 10:07
I also get this issue. With a copy paste of the example code I get the result below regardless of clicking either button.

<img width="184" alt="Screen Shot 2021-07-07 at 8 03 30 pm" src="https://user-images.githubusercontent.com/3204020/124741051-ac907400-df5e-11eb-868a-80254a0aab50.png">

DateTimePicker: 3.5.2
Expo: 4.7.2
iOS: 14.5

**Comment by sofian-io** [comment] 2021-07-07 13:19
Hi Guys seems to be a duplicate of this ticket: https://github.com/react-native-datetimepicker/datetimepicker/issues/420#issuecomment-808829227

This is an issue with the 'default' display, if for iOS you switch to 'inline' display and open in a modal as the link above suggest you should be able to get the desired result. 

On android 'default' display works as expected, would be nice if the 'default' display behavior for iOS could be updated in this package as well.

**Comment by caolong0204** [comment] 2021-07-07 14:16
> I have the same issue on iOS 14.5 the setShow(true) only displays the time picker (gray box in screenshot below) and you need to press it again to open the time picker modal.
> 
> datetimepicker version: 3.5.2
> 
> iOS version: 14.5
> 
> <img alt="Screenshot 2021-07-05 at 14 13 39" width="288" src="https://user-images.githubusercontent.com/11960001/124469930-40b1de00-dd9b-11eb-9a9e-5ccff495d0f5.png">

But i didn't see anything same as you say

**Comment by caolong0204** [comment] 2021-07-07 14:34
> Hi Guys seems to be a duplicate of this ticket: [#420 (comment)](https://github.com/react-native-datetimepicker/datetimepicker/issues/420#issuecomment-808829227)
> 
> This is an issue with the 'default' display, if for iOS you switch to 'inline' display and open in a modal as the link above suggest you should be able to get the desired result.
> 
> On android 'default' display works as expected, would be nice if the 'default' display behavior for iOS could be updated in this package as well.

tks for your answer, but if the steps in video is required to it can work then it's so annoying, i think that it's a bug, need to fix soon

**Comment by caolong0204** [comment] 2021-07-12 04:30
i used to temporary solution that @sofian-io share, and app worked, so i will set closed this issue.
But if the steps in the video are necessary to run on ios then it should be added to the documentation

**Closed** 2021-07-23 01:58 UTC

**Comment by rassemdev** [comment] 2022-10-11 17:30
I'm also having same problem, after updating my xcode to 14, calendar picker not showing, only showing spinner.
