### ISSUE TITLE
Can't see iOS 14 style

### ISSUE THREAD

**Issue by Michaelmala** [react-native-datetimepicker/datetimepicker#328] opened 2020-11-04 21:32 UTC
Hi! I' m using the latest version of the package (3.0.4) but the picker style is like iOS 13. I don' t know why but I' m not able to see the iOS 14 style.

This is the screenshot:

<img width="524" alt="Schermata 2020-11-04 alle 22 32 07" src="https://user-images.githubusercontent.com/62499654/98170025-94f37e00-1eed-11eb-8bd3-7cf79d7d71ec.png">

**Comment by luancurti** [comment] 2020-11-05 14:06
@Michaelmala Please follow the template to the maintainers can help you

**Comment by vonovak** [comment] 2020-11-05 17:16
@luancurti there is no issue template after we moved out of RNC :D

I'll try to fix it soon

**Comment by ignaciosantise** [comment] 2020-11-05 17:45
@Michaelmala did you run `pod install` after updating the version? Im running 3.0.4 in iOS 14 and its showing the new style

![Nov-05-2020 14-44-28](https://user-images.githubusercontent.com/25931366/98276969-8650a980-1f75-11eb-9398-06cf03db2f93.gif)

**Comment by Michaelmala** [comment] 2020-11-05 21:20
@ignaciosantise I'm using expo so I don't have an xCode project

**Comment by vonovak** [comment] 2020-11-05 23:52
closing as duplicate of https://github.com/react-native-datetimepicker/datetimepicker/issues/317

**Closed by vonovak** 2020-11-05 23:52 UTC
