### ISSUE TITLE
./node_modules/@react-native-community/datetimepicker/src/androidUtils.js:6 Module not found: Can't resolve './picker'

### ISSUE THREAD

**Issue by Don-peter-joseph** [react-native-datetimepicker/datetimepicker#623] opened 2022-06-18 15:12 UTC
# Bug report

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. …
2. …

## Environment info

`npx react-native info` output:

```bash
# paste it here
```

datetimepicker version: x.x.x

iOS / Android version: x.x

**Comment by vonovak** [comment] 2022-06-27 21:28
:tada: This issue has been resolved in version 6.1.4 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:

**Comment by vonovak** [comment] 2022-06-29 09:29
> > tada This issue has been resolved in version 6.1.4 tada
> 
> > 
> 
> > If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! rocket
> 
> 
> 
> @vonovak 
> 
> 
> 
> Expo still links to version `6.1.2` causing build problems:
> 
> ```
> 
> > expo install @react-native-community/datetimepicker
> 
> Installing 1 SDK 45.0.0 compatible native module using Yarn.
> 
> ```

Hello, in this case you can force your package manager to update to 6.1.4 and it should work just fine.

Thank you

**Comment by tamis-laan** [comment] 2022-06-29 09:33
@vonovak

I did `yarn add @react-native-community/datetimepicker` which takes me to `6.2.1` but I'm not sure if this will bring problems in the future. For example running `expo install` will downgrade datetimepicker?

**Comment by vonovak** [comment] 2022-06-29 10:31
> @vonovak
> 
> I did `yarn add @react-native-community/datetimepicker` which takes me to `6.2.1` but I'm not sure if this will bring problems in the future. For example running `expo install` will downgrade datetimepicker?

Hello,
the latest version is 6.2.0 so I don't think it's possible to use 6.2.1 😄.
That being said, 6.2.0 already has features that you cannot use in your setup, so please use 6.1.4 as I indicated above.

> For example running `expo install` will downgrade datetimepicker?

I don't think it will downgrade but you can run it and see it or yourself 🙂. I hope I'm correct here and it works, if not I suggest you take the changes from #625 and apply them using patch-package.

Hope this helps, thank you 🙂

**Comment by vonovak** [comment] 2022-06-29 14:05
yes, that is expected. But if 6.1.4 works than the problem is solved, no? 🤔  🙂

**Comment by vonovak** [comment] 2022-06-29 15:09
in that case, please refer to this part of my previous comment:

> I don't think it will downgrade but you can run it and see it or yourself 🙂. I hope I'm correct here and it works, if not I suggest you take the changes from https://github.com/react-native-datetimepicker/datetimepicker/pull/625 and apply them using patch-package.

Thank you 🙂

**Closed** 2022-06-29 15:09 UTC
Labels: released
