### ISSUE TITLE
date picker returns next day on clicking OK on android

### ISSUE THREAD

**Issue by abidhkm** [react-native-datetimepicker/datetimepicker#474] opened 2021-06-04 15:03 UTC
I'm facing one issue, Replicated that here https://snack.expo.io/pxAMzLcyP

When running it on android, the date changes to the next day upon clicking the button 'ok' multiple times even though the date in the picker is not changed.

**Comment by xdajay** [comment] 2021-06-09 05:45
I've faced the same issue with directly using state in value prop, instead use this `value={new Date(this.state.clock)}`

**Comment by sanjeevkse** [comment] 2021-06-22 04:13
@xdajay Thats a solution. It got fixed.
But it repeats,
1. When we click on the same selected date and press ok. 
2. When we click on the next date and click back on the same date and press ok (sometimes)

**Comment by abidhkm** [comment] 2021-06-22 06:56
I fixed the issue by deleting the prop timeZoneOffsetInMinutes.

**Comment by akmallmr** [comment] 2021-08-05 07:57
> Wrapping value within Date didn't help me, value={new Date(this.state.clock)}
> I fixed the issue by deleting the prop timeZoneOffsetInMinutes.

Thank you, sir.. This solved for me..

**Comment by Ashutosh-Tiwari** [comment] 2021-08-18 09:21
Any fix for this issue?

**Comment by akmallmr** [comment] 2021-08-18 09:26
> Any fix for this issue?

If you have any datepickers props named **timeZoneOffsetInMinutes**, then you have to removed it @Ashutosh-Tiwari.. Last week I have a same issues, and I removed the **timeZoneOffsetInMinutes** props and it works for me..

**Comment by vonovak** [comment] 2021-12-11 23:22
duplicate of https://github.com/react-native-datetimepicker/datetimepicker/issues/528

**Closed by vonovak** 2021-12-11 23:22 UTC
