### ISSUE TITLE
seeing spinner in expo project

### ISSUE THREAD

**Issue by chrisdrackett** [react-native-datetimepicker/datetimepicker#317] opened 2020-10-23 23:33 UTC
I've installed version 3.0.0 via expo and tried to use the 'inline' display option, but I'm still seeing the spinner view.

Snack: https://snack.expo.io/@tiltshift/datetimepicker-display

Is expo actually built against an older version? am I doing something else wrong?

**Comment by vonovak** [comment] 2020-10-24 11:13
hello Chris!
firstly, thank you for backing us! It is very much appreciated! 🙂 

regarding the `display` prop [docs](https://github.com/react-native-datetimepicker/datetimepicker#display-optional)

the prop is supported since iOS 14 (as documented), but the appetize device runs iOS 13.3. That is probably why it has no effect there.

<img width="385" alt="Screen Shot 2020-10-24 at 13 12 45" src="https://user-images.githubusercontent.com/1566403/97080308-a63db000-15fa-11eb-865f-d5179a890f9d.png">
 

Hope this answers the question.

**Comment by chrisdrackett** [comment] 2020-10-24 16:03
Right, but I’m opening the snack on a device and/or simulator that is running 14.1. Both using the expo app

**Comment by vonovak** [comment] 2020-10-24 18:03
@chrisdrackett I confirm I can reproduce this when I download the snack and run it locally in an ios 14 simulator

I'm afraid this is a bug in expo; when I run `expo eject`, and build the resulting project in xcode, all works fine. Somehow [this code](https://github.com/expo/expo/blob/4f689b3ec5b17692e9a5fd1e9d9769ae9c419e6c/ios/versioned-react-native/ABI39_0_0/Expo/ExpoKit/Core/Api/Components/DateTimePicker/ABI39_0_0RNDateTimePickerManager.m#L105) does not work properly in Expo. It's kinda weird that it falls back to "spinner" display (=`UIDatePickerStyleWheels`), not sure why 🤔 

I recommend that you open an issue in the expo repository and link them to this issue / comments. Sorry I don't have better news, but I don't think the bug is in this repository.

**Comment by chrisdrackett** [comment] 2020-10-26 23:12
thanks!

**Comment by vonovak** [comment] 2021-12-11 14:52
I believe this should be resolved by now :)

**Closed by vonovak** 2021-12-11 14:52 UTC
