### ISSUE TITLE
onChange is not working on pressing ok button from calendar.

### ISSUE THREAD

**Issue by PrashantPermi** [react-native-datetimepicker/datetimepicker#599] opened 2022-04-18 09:16 UTC
# Bug report

## Reproducible sample code

```
export const App = () => {
  const [date, setDate] = useState(new Date(1598051730000));
  const [mode, setMode] = useState('date');
  const [show, setShow] = useState(false);

  const onChange = (event, selectedDate) => {
    const currentDate = selectedDate;
    setShow(false);
    setDate(currentDate);
  };

  const showMode = (currentMode) => {
    setShow(true);
    setMode(currentMode);
  };

  const showDatepicker = () => {
    showMode('date');
  };

  const showTimepicker = () => {
    showMode('time');
  };

  return (
    <View>
      <View>
        <Button onPress={showDatepicker} title="Show date picker!" />
      </View>
      <View>
        <Button onPress={showTimepicker} title="Show time picker!" />
      </View>
      <Text>selected: {date.toLocaleString()}</Text>
      {show && (
        <DateTimePicker
          testID="dateTimePicker"
          value={date}
          mode={mode}
          is24Hour={true}
          onChange={onChange}
        />
      )}
    </View>
  );
}
```

datetimepicker version: 6.1.2
iOS / Android version: 10
react: 17.0.2
react-native: 0.67.3

**Comment by arisyo13** [comment] 2022-05-20 11:57
There is not a bug. The onChangemethod returns back a `Date` object but on your onChange method you have two parameters `event, selectedDate` and you are not using event which in this case is the date object

**Comment by PrashantPermi** [comment] 2022-05-31 07:34
@arisyo13 `onChange` prop itself is not working.

**Comment by vonovak** [comment] 2022-07-25 21:19
Hello and thanks for reporting,
I just tried to reproduce it using the provided code, using an android 10 emulator. I was not able to reproduce and so I'm going to close the issue. Please open a new issue if the problem persists.
Thank you 🙂

**Closed by vonovak** 2022-07-25 21:19 UTC
