### ISSUE TITLE
Android minimumDate and maximumDate not working

### ISSUE THREAD

**Issue by VolodymyrErsteniuk** [react-native-datetimepicker/datetimepicker#84] opened 2020-01-10 14:20 UTC
# Bug

DateTimePicker ignores minimumDate and maximumDate properties. On IOS it works fine.
As a workaround any logic can be done inside onChange

## Environment info
React native info output:

```bash
 System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 1.12 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5
```

Library version: 2.1.0

## Reproducible sample code

```
if (Platform.OS === 'android') {
    return (
      <DateTimePicker
        value={dateValue}
        mode={mode}
        minimumDate={minimumDate}
        maximumDate={maximumDate}
        display="spinner"
        onChange={(e, date) => {
          if (date === undefined) {
            onDismiss();
          } else {
            if (minimumDate && date < minimumDate) {
              console.log('LOWER THAT MINIMUM DATE');
            } else if (maximumDate && date > maximumDate) {
              console.log('BIGGER THAN MAXIMUM DATE');
            } else {
              onChange(date);
            }
          }
        }}
      />
    );
  }
```

**Comment by georgeMorales** [comment] 2020-01-15 11:04
minimumDate and maximumDate still not working?

**Comment by ChinmayDeyUI** [comment] 2020-01-22 11:51
Same issue here

**Comment by mjschutz** [comment] 2020-01-23 12:30
For me it's ignoring the minimumDate, the maximumDate is working.

**Comment by Bran72** [comment] 2020-01-24 10:10
Hey, this bug also is in iOS.
I confirm what @mjschutz said, if minimumDate & maximumDate has same value, minimumDate is ignored. BUT in fact, if maximumDate props is passed without a well value, minimumDate doesn't work.

I've 'patched' this by setting a condition in the RNDateTimePicker component' props:
`<DatePicker
    value={this.state.selectedDate}
    minimumDate={ minDate || null }
    maximumDate={ maxDate || null }
    onChange={(e, date) => this.setState({selectedDate: date}) }
/>`

Hope this will help !

**Comment by albullington** [comment] 2020-03-09 22:44
I'm seeing this bug on Android when using `mode="datetime"` and setting `maximumDate={new Date()}`.

The date part of maximumDate works fine, but the **time** part allows a user to input a time hours in the future.

On iOS, everything works as expected.

**Comment by magrinj** [comment] 2020-05-01 18:57
On my side, the problems happen only in `time` mode, in `date` mode, everything seems to work properly, the date before or after the minimum and maximum are grey and not clickable, but unfortunately when the picker is in `time` mode, I totally can select a time before the minimumDate.

**Comment by natasha08n** [comment] 2020-05-25 11:05
For me `minimumDate` doesn't work on iOS even if minimumDate is less then maximumDate
```
maximumDate={new Date('2020-05-25T11:00:51.642Z')}
mimimumDate={new Date('2018-05-25T11:00:51.642Z')}
```

**Comment by mirfanahmed** [comment] 2020-07-26 06:56
Hello. How Can I set Minimum Time? If anyone have wrote its own code for time so kindly share it..

**Comment by AKclown** [comment] 2020-08-11 06:09
> On my side, the problems happen only in `time` mode, in `date` mode, everything seems to work properly, the date before or after the minimum and maximum are grey and not clickable, but unfortunately when the picker is in `time` mode, I totally can select a time before the minimumDate.
> Everything is ok on iOS, problem is only on Android side.
> 
> EDIT:
> Seems that for a `TimePicker` on Android side this option is not available, I think it need to be precise in the Readme
> 
> https://github.com/react-native-community/datetimepicker/blob/58218994a599232dedee80762373c56429585082/src/datetimepicker.android.js#L47

yes ，   I also faced the same problem

**Comment by mirfanahmed** [comment] 2020-08-11 06:44
> > On my side, the problems happen only in `time` mode, in `date` mode, everything seems to work properly, the date before or after the minimum and maximum are grey and not clickable, but unfortunately when the picker is in `time` mode, I totally can select a time before the minimumDate.
> > Everything is ok on iOS, problem is only on Android side.
> > EDIT:
> > Seems that for a `TimePicker` on Android side this option is not available, I think it need to be precise in the Readme
> > https://github.com/react-native-community/datetimepicker/blob/58218994a599232dedee80762373c56429585082/src/datetimepicker.android.js#L47
> 
> yes ， I also faced the same problem

for minimum time, i need to write my own code..

**Comment by jguix** [comment] 2021-01-21 11:12
I also experienced this bug. It's not coherent with the iOS behavior, where it won't let you select a future time if a maximumDate was set.

**Comment by vonovak** [comment] 2021-01-21 12:53
hello, I'm closing this issue because the issue template was not fully followed and it is thus not clear if a bug is really present and how it can be reproduced (the code snippet at the top is not runnable).

On Android, min and max dates only work in date mode, not in time mode, as documented. If you're having this issue with time picker than this is the expected behavior at the moment because the native control does not support min and max dates and you'll have to implement such limits yourself based on how your app's needs.

Thank you!

**Closed by vonovak** 2021-01-21 12:53 UTC

**Comment by anarkrypto** [comment] 2023-03-23 00:38
A simple solution with a handler

```js
      const handleChange = (e, date) => {
        if (date < minimumDate || date > maximumDate) {
          return Alert.alert(
                       "Invalid Datetime",
                       `Cannot be less than ${minimumDate} or greater than ${maximumDate}`
          ).
        }
        // passed, make something
        ....
     }
```

**Comment by Numan-Munir** [comment] 2023-05-11 10:40
I also experienced this bug. Is there any solution?

**Comment by AyoCodess** [comment] 2023-11-28 20:39
does not work on android

**Comment by danyalutsevich** [comment] 2024-03-14 14:11
is min and max date for time still not available?
