### ISSUE TITLE
Doesn't work well when we rotate from Landscape to Portrait

### ISSUE THREAD

**Issue by gaurangmajithiya** [react-native-datetimepicker/datetimepicker#332] opened 2020-11-11 12:11 UTC
Hi,

We are using this datepicker in React Native app with Expo (SDK 39).

![Screenshot_2020-11-11-10-07-13-251_host exp exponent](https://user-images.githubusercontent.com/8628256/98805334-6de10300-243d-11eb-9e13-82df44379fee.jpg)

![issue](https://user-images.githubusercontent.com/8628256/98809839-3c1f6a80-2444-11eb-804e-94f8ccb18877.gif)

**Steps to reproduce**
- Open DatePicker in landscape mode
- Keep DatePicker open and rotate device to Portrait mode

You will see the issue similar to shown in above screenshot.

**Expected Behaviour**
- When we open DatePicker in landscape mode, it opens nicely with proper landscape format
- When we rotate device screen while keeping calendar open it should detect current orientation and should convert DatePicket in portrait format.

Here I am attaching sample code. You can run this code using `expo start` command, it will open a screen of expo in browser and scan QR code from the browser in your device (your device must have Expo App installed).

[date-picker-standalone.zip](https://github.com/react-native-datetimepicker/datetimepicker/files/5523668/date-picker-standalone.zip)

Thanks,
Gaurang

**Comment by vonovak** [comment] 2021-03-17 17:54
duplicate of  #49

**Closed by vonovak** 2021-03-17 17:54 UTC
