### ISSUE TITLE
Cannot choose earlier or future date in iOS 14.3 devices

### ISSUE THREAD

**Issue by Maharshi01** [react-native-datetimepicker/datetimepicker#393] opened 2021-02-05 10:31 UTC
# Bug report

## Summary

Iam unable to select earlier or future date only in iOS 14.3 device, in other andorid or iOS devices i am able to select though.....

Can tell what's the issue with 14.3 iOS version only...

For your reference i attached a video and image...

## Reproducible sample code

<DateTimePicker
cancelTextStyle={{ color: '#173154' }}
isVisible={this.state.showTime}
onConfirm={this.handleTimePicked}
title={strings.customerSupport.Set_Time}
is24Hour={false}
titleIOS={strings.customerSupport.setTime}
mode={"time"}
maximumDate={this.state.date === moment(new Date()).format('DD MMM YYYY') ? new Date() : null}
onCancel={this.hideTimePicker}
isDarkModeEnabled={false}
/>

## Steps to reproduce

1. …Copy paste this code snippet in your code
2. …Run the program in iOS 14.3 device only

Describe what you expected to happen:

1. …I wish i can able to select date before today but not beyond today

## Environment info

`npx react-native info` output:

```bash
iOS: 14.3
react-native-modal-datetime-picker: 9.1.0
react-native-community/datetimepicker: 3.0.9
react-native: 0.61.2
react: 16.9.0
```

datetimepicker version: 3.0.9
iOS / Android version: 14.3
![106839518-5e7ff780-66c4-11eb-9b97-f4c9342a4b0a](https://user-images.githubusercontent.com/48430425/107022156-0e3f8d00-67cb-11eb-89e6-fc07a38d147e.png)

https://user-images.githubusercontent.com/48430425/107022182-1697c800-67cb-11eb-841c-1e373364824c.mp4

Proof that it is working in other iOS versions
![106915035-9a9a7300-672b-11eb-9fa1-e458b5b299ce](https://user-images.githubusercontent.com/48430425/107022369-4f37a180-67cb-11eb-81ff-f3c6e1607ccd.jpeg)

**Comment by vonovak** [comment] 2021-02-05 12:07
hello, and thanks for reporting, your snippet cannot be copy-pasted into someone else's codebase: what is `this.state.showTime`, `this.state.date` and other things in the code? We don't know. Please provide a runnable snippet without dependency on `react-native-modal-datetime-picker`. The issue must be reproducible with only `react-native-community/datetimepicker`.

Then the issue is actionable. Without this, I will close it. Thank you for your understanding.

**Comment by appdev-cts** [comment] 2021-02-15 10:38
can't show date & time in datetime modal picker ?
![Uploading Simulator Screen Shot - iPhone 8 - 2021-02-15 at 16.02.35.png…]()

**Closed** 2021-02-15 13:10 UTC
Labels: repro-required
