### ISSUE TITLE
[iOS]"mode='datetime' display='inline'" Time view height issue

### ISSUE THREAD

**Issue by Inocentum** [react-native-datetimepicker/datetimepicker#683] opened 2022-10-27 03:59 UTC
# Bug report

## Summary

The Time section in the DateTimePicker has very low height. The current or selected time is not visible on iOS in display='inline' settings. 

## Reproducible sample code

`<DateTimePicker
        value={startDateTime}
        mode="datetime"
        display={Platform.OS === 'ios' ? 'inline' : 'default'}
        onConfirm={date => {
                // perform your action here...
        }}
        onCancel={date => {
                // perform your action here...
        }}
/>`
## Steps to reproduce
It's a simple import and adding the DateTimePicker in your View anywhere with mode set to datetime and display set to inline.

## Environment info

`npx react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 97.17 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.5 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Time zone name: User Default. Have the same issue in India (IST, GMT + 5:30) and USA (Watcher Wy, Apex, NC 27502, USA)

datetimepicker version: 6.5.3
(Have been having this issue since past couple of months with various versions of datetimepicker)

iOS / Android version: iOS 15.4, iOS 16, iOS 16.0.1, iOS 16.0.3

Screenshot: https://drive.google.com/file/d/19LN_kCQA1vNEzzSY35WwJP4uyiIyy3Wy/view?usp=sharing

**Comment by vonovak** [comment] 2022-10-27 07:06
Hello and thanks for reporting,
I cannot repro this, please add a minimum reproducible code, otherwise I'll close this.


<details>
  <summary>screenshot</summary>

![Simulator Screen Shot - iPhone 14 Pro - 2022-10-27 at 09 04 24](https://user-images.githubusercontent.com/1566403/198214232-0cf06241-4d19-4786-a710-9a3d9e586b8a.png)

</details>



Thank you 🙂

**Comment by Inocentum** [comment] 2022-10-27 07:19
```jsx
<View style={{flex: 1}}>
    <DateTimePicker
        value={startDateTime} 
        mode="datetime" 
        display={Platform.OS === 'ios' ? 'inline' : 'default'} 
        onConfirm={date => { 
            // perform your action here...
        }} 
        onCancel={date => { 
            // perform your action here...
        }}
    />
</View>
```

Try this.

**Comment by vonovak** [comment] 2022-10-27 08:19
Thank you. 🙂 
Not sure what the issue is, but wrapping your view in `SafeAreaView` resolves the problem.

**Closed by vonovak** 2022-10-27 08:19 UTC

**Comment by Inocentum** [comment] 2022-10-27 09:07
This is also a possible workaround:

```jsx
<View style={{flex: 1}}>
    <DateTimePicker
        value={new Date()}
        mode="datetime"
        display={Platform.OS === 'ios' ? 'inline' : 'default'}
        style={{flex: 1}}
    />
</View>
```

But the issue arises in react-native-modal-datetime-picker which depends upon this module.
```jsx
<DateTimePickerModal
    date={startDateTime}
    mode="datetime"
    display={Platform.OS === 'ios' ? 'inline' : 'default'}
    style={{minHeight: height * 0.45, maxHeight: height * 0.5}}
    isVisible={selectStartDateTime}
/>
```
For that the workaround I have found is setting a minHeight/height style to a value which makes the Time View visible properly [Users will have to try different values as per their requirement].

They won't entertain this as the issue originates from this module.
